import { LocaleCode, normalizeLocale } from './index';

export type CardCopy = {
  travelPass: string; travelMemory: string; memory: string; admitOne: string; journeyRecord: string;
  boardingPass: string; museumEntry: string; ticketDetails: string; serial: string; date: string;
  location: string; note: string; diveLog: string; marineLife: string; unnamedDive: string;
  diveLabels: [string, string, string, string, string, string, string];
};

export const cardCopyByLocale: Record<LocaleCode, CardCopy> = {
  en: { travelPass: 'Travel Pass', travelMemory: 'Travel Memory', memory: 'Memory', admitOne: 'Admit One', journeyRecord: 'Journey Record', boardingPass: 'Boarding Pass', museumEntry: 'Museum Entry', ticketDetails: 'Ticket Details', serial: 'Serial', date: 'Date', location: 'Location', note: 'Note', diveLog: 'Dive Log', marineLife: 'Marine Life', unnamedDive: 'Dive Site', diveLabels: ['Site', 'Max Depth', 'Duration', 'Water', 'Visibility', 'Buddy', 'Marine Life'] },
  zh: { travelPass: '旅行票', travelMemory: '旅行纪念', memory: '纪念', admitOne: '入场券', journeyRecord: '旅程记录', boardingPass: '登机牌', museumEntry: '博物馆入场券', ticketDetails: '票根信息', serial: '编号', date: '日期', location: '地点', note: '备注', diveLog: '潜水日志', marineLife: '遇见的生物', unnamedDive: '未命名潜点', diveLabels: ['潜点', '最大深度', '潜水时长', '水温', '能见度', '潜伴', '遇见的生物'] },
  ja: { travelPass: 'トラベルパス', travelMemory: '旅の記憶', memory: '思い出', admitOne: '入場券', journeyRecord: '旅の記録', boardingPass: '搭乗券', museumEntry: '美術館入場券', ticketDetails: 'チケット情報', serial: '番号', date: '日付', location: '場所', note: 'メモ', diveLog: 'ダイビングログ', marineLife: '出会った生き物', unnamedDive: 'ダイビングポイント', diveLabels: ['ポイント', '最大深度', '潜水時間', '水温', '透明度', 'バディ', '出会った生き物'] },
  ko: { travelPass: '여행 티켓', travelMemory: '여행의 기억', memory: '추억', admitOne: '입장권', journeyRecord: '여정 기록', boardingPass: '탑승권', museumEntry: '박물관 입장권', ticketDetails: '티켓 정보', serial: '번호', date: '날짜', location: '장소', note: '메모', diveLog: '다이빙 로그', marineLife: '관찰 생물', unnamedDive: '다이빙 포인트', diveLabels: ['포인트', '최대 수심', '다이빙 시간', '수온', '시야', '버디', '관찰 생물'] },
  fr: { travelPass: 'Pass Voyage', travelMemory: 'Souvenir de Voyage', memory: 'Souvenir', admitOne: 'Entrée', journeyRecord: 'Carnet de Voyage', boardingPass: 'Carte d’Embarquement', museumEntry: 'Entrée Musée', ticketDetails: 'Détails du Billet', serial: 'Numéro', date: 'Date', location: 'Lieu', note: 'Note', diveLog: 'Carnet de Plongée', marineLife: 'Vie Marine', unnamedDive: 'Site de Plongée', diveLabels: ['Site', 'Profondeur Max.', 'Durée', 'Eau', 'Visibilité', 'Binôme', 'Vie Marine'] },
  de: { travelPass: 'Reisepass', travelMemory: 'Reiseerinnerung', memory: 'Erinnerung', admitOne: 'Eintritt', journeyRecord: 'Reiseprotokoll', boardingPass: 'Bordkarte', museumEntry: 'Museumseintritt', ticketDetails: 'Ticketdetails', serial: 'Nummer', date: 'Datum', location: 'Ort', note: 'Notiz', diveLog: 'Tauchprotokoll', marineLife: 'Meeresleben', unnamedDive: 'Tauchplatz', diveLabels: ['Tauchplatz', 'Max. Tiefe', 'Dauer', 'Wasser', 'Sicht', 'Buddy', 'Meeresleben'] },
  es: { travelPass: 'Pase de Viaje', travelMemory: 'Recuerdo de Viaje', memory: 'Recuerdo', admitOne: 'Entrada', journeyRecord: 'Registro de Viaje', boardingPass: 'Tarjeta de Embarque', museumEntry: 'Entrada al Museo', ticketDetails: 'Detalles del Billete', serial: 'Número', date: 'Fecha', location: 'Lugar', note: 'Nota', diveLog: 'Registro de Buceo', marineLife: 'Vida Marina', unnamedDive: 'Punto de Buceo', diveLabels: ['Punto', 'Prof. Máxima', 'Duración', 'Agua', 'Visibilidad', 'Compañero', 'Vida Marina'] },
  it: { travelPass: 'Pass di Viaggio', travelMemory: 'Ricordo di Viaggio', memory: 'Ricordo', admitOne: 'Ingresso', journeyRecord: 'Diario di Viaggio', boardingPass: 'Carta d’Imbarco', museumEntry: 'Ingresso Museo', ticketDetails: 'Dettagli Biglietto', serial: 'Numero', date: 'Data', location: 'Luogo', note: 'Nota', diveLog: 'Registro Immersione', marineLife: 'Vita Marina', unnamedDive: 'Sito d’Immersione', diveLabels: ['Sito', 'Profondità Max.', 'Durata', 'Acqua', 'Visibilità', 'Compagno', 'Vita Marina'] },
  th: { travelPass: 'บัตรเดินทาง', travelMemory: 'ความทรงจำจากการเดินทาง', memory: 'ความทรงจำ', admitOne: 'บัตรเข้าชม', journeyRecord: 'บันทึกการเดินทาง', boardingPass: 'บัตรขึ้นเครื่อง', museumEntry: 'บัตรเข้าพิพิธภัณฑ์', ticketDetails: 'รายละเอียดบัตร', serial: 'หมายเลข', date: 'วันที่', location: 'สถานที่', note: 'บันทึก', diveLog: 'บันทึกการดำน้ำ', marineLife: 'สิ่งมีชีวิตใต้ทะเล', unnamedDive: 'จุดดำน้ำ', diveLabels: ['จุดดำน้ำ', 'ความลึกสูงสุด', 'ระยะเวลา', 'อุณหภูมิน้ำ', 'ทัศนวิสัย', 'บัดดี้', 'สิ่งมีชีวิตใต้ทะเล'] },
  vi: { travelPass: 'Vé Du Lịch', travelMemory: 'Kỷ Niệm Chuyến Đi', memory: 'Kỷ Niệm', admitOne: 'Vé Vào Cửa', journeyRecord: 'Nhật Ký Hành Trình', boardingPass: 'Thẻ Lên Máy Bay', museumEntry: 'Vé Bảo Tàng', ticketDetails: 'Thông Tin Vé', serial: 'Mã Số', date: 'Ngày', location: 'Địa Điểm', note: 'Ghi Chú', diveLog: 'Nhật Ký Lặn', marineLife: 'Sinh Vật Biển', unnamedDive: 'Điểm Lặn', diveLabels: ['Điểm Lặn', 'Độ Sâu Tối Đa', 'Thời Gian', 'Nhiệt Độ Nước', 'Tầm Nhìn', 'Bạn Lặn', 'Sinh Vật Biển'] },
  id: { travelPass: 'Tiket Perjalanan', travelMemory: 'Kenangan Perjalanan', memory: 'Kenangan', admitOne: 'Tiket Masuk', journeyRecord: 'Catatan Perjalanan', boardingPass: 'Kartu Naik', museumEntry: 'Tiket Museum', ticketDetails: 'Detail Tiket', serial: 'Nomor', date: 'Tanggal', location: 'Lokasi', note: 'Catatan', diveLog: 'Log Menyelam', marineLife: 'Biota Laut', unnamedDive: 'Lokasi Selam', diveLabels: ['Lokasi', 'Kedalaman Maks.', 'Durasi', 'Suhu Air', 'Jarak Pandang', 'Buddy', 'Biota Laut'] },
  ms: { travelPass: 'Pas Perjalanan', travelMemory: 'Kenangan Perjalanan', memory: 'Kenangan', admitOne: 'Tiket Masuk', journeyRecord: 'Catatan Perjalanan', boardingPass: 'Pas Masuk Pesawat', museumEntry: 'Tiket Muzium', ticketDetails: 'Butiran Tiket', serial: 'Nombor', date: 'Tarikh', location: 'Lokasi', note: 'Catatan', diveLog: 'Log Selaman', marineLife: 'Hidupan Marin', unnamedDive: 'Tapak Selaman', diveLabels: ['Tapak', 'Kedalaman Maks.', 'Tempoh', 'Suhu Air', 'Jarak Penglihatan', 'Rakan Selam', 'Hidupan Marin'] },
};

export const getCardCopy = (locale: string) => cardCopyByLocale[normalizeLocale(locale)];
